authbind: true
mysql-pass: password
mysql-host: localhost
gzip: true
buffer.out: 1048576
mysql-db: database
hostname: localhost
mysql-port: 3306
ipv4: false
port: 8080
mysql-user: changeme
buffer.in: 1048576
buffer: 134217728
mysql-enabled: false
