authbind: true
hostname: localhost
ipv4: false
port: 8080
gzip: true
buffer.in: 1048576
buffer: 134217728
buffer.out: 1048576
mysql-enabled: false
mysql-host: localhost
mysql-db: database
mysql-port: 3306
mysql-user: changeme
mysql-pass: password